copyright_holders: |
  Gennady Bystritsky <bystr@mac.com>

license: |
  Distributed under the MIT Licence.
  This is free software. See 'LICENSE' for details.
  You must read and accept the license prior to use.

cpp:
  default:
    like: sk-default
        
  test:
    like: cppunit-test

  suite:
    like: cppunit-sk-suite

